<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>multiple-info</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2151d84f-4217-42c9-85c6-ee73b63dd7a0</testSuiteGuid>
   <testCaseLink>
      <guid>41e99850-2fc6-4bbf-a6a0-f5d7186b6876</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/SK002-Shopping_cart/TC001-Checkout_product</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ed79fff4-701c-4bd0-96df-8f29fd620d15</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data-info</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ed79fff4-701c-4bd0-96df-8f29fd620d15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>first_name</value>
         <variableId>473b76b0-3af7-4e61-9911-3635a50b4a1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ed79fff4-701c-4bd0-96df-8f29fd620d15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>last_name</value>
         <variableId>5c0bfc47-16cf-422c-916d-4ab1c4bd848c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ed79fff4-701c-4bd0-96df-8f29fd620d15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>zip/postal_code</value>
         <variableId>00dd1954-45ab-49f8-ba91-e89e87053795</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
